---
- name: Sauvegarde de la configuration courante en NVRAM (Avant migration)
  cisco.ios.ios_command:
    commands:
      - command: "write memory"
  register: save_output
  changed_when: "'OK' in save_output.stdout[0]"

- name: Afficher la confirmation du switch
  ansible.builtin.debug:
    var: save_output.stdout_lines