---
- name: verification router phase
  hosts: routers
  gather_facts: false
  become: yes                 
  become_method: enable

  roles:
    - router_provisioning 

- name: switches installation
  hosts: switches
  gather_facts: false 
  become: yes
  become_method: enable

  roles:
    - switch_provisioning