---
# /home/elpetrino/projet/roles/router_provisioning/tasks/01-Backup.yml

- name: Recuperer la configuration courante
  cisco.ios.ios_facts:
    gather_subset:
      - config

- name: S'assurer que le dossier des backups existe localement
  ansible.builtin.file:
    path: "./backups/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: false

- name: Sauvegarder le fichier horodate localement
  ansible.builtin.copy:
    content: "{{ ansible_net_config }}"
    dest: "./backups/{{ inventory_hostname }}/{{ now(fmt='%Y-%m-%d_%Hh%M') }}.cfg"
  delegate_to: localhost