---
- name: Desactivation des services non securises
  cisco.ios.ios_config:
    lines:
      - no ip http server
      - no ip http secure-server
      - no ip source-route

- name: Configuration des ACLs standardisees pour le VTY
  cisco.ios.ios_config:
    parents: ip access-list standard ACL_VTY_IN
    lines:
      - permit {{ management_subnet }} {{ management_wildcard }}
  when: management_subnet is defined
