---
# roles/router_provisioning/tasks/05-Routing.yml

- name: Creation du processus OSPF global (Module Natif)
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: "{{ ospf_process_id | int }}"
          router_id: "{{ ospf_router_id }}"
  when: enable_ospf | default(false)

- name: Association dynamique des interfaces a l'aire OSPF (Module Natif)
  cisco.ios.ios_ospf_interfaces:
    config:
      - name: "{{ item.name }}"
        address_family:
          - afi: ipv4
            process:
              id: "{{ ospf_process_id | int }}"      # <--- Change de 'pid' a 'id'
              area_id: "{{ ospf_area_id | default('0') }}"  # <--- Change de 'area' a 'area_id'
  loop: "{{ network_interfaces }}"
  when: 
    - enable_ospf | default(false) 
    - network_interfaces is defined 
    - item.ospf_enabled | default(false)

- name: Configuration BGP via module natif
  cisco.ios.ios_bgp_global:    
    config:
      as_number: "{{ bgp_local_as | default(65000) }}"
      neighbors:
        - neighbor: "{{ bgp_neighbor_ip | default('0.0.0.0') }}"
          remote_as: "{{ bgp_neighbor_as | default(65000) }}"
  when: enable_bgp | default(false)