---
# /home/elpetrino/projet/roles/router_provisioning/tasks/06-acl_nat.yml

- name: "Tagging de l'interface WAN (NAT Outside)"
  cisco.ios.ios_config:
    parents: "interface {{ interface_nat_outside }}"
    lines:
      - ip nat outside
  when: interface_nat_outside is defined

- name: "Tagging des interfaces LAN (NAT Inside)"
  cisco.ios.ios_config:
    parents: "interface {{ item }}"
    lines:
      - ip nat inside
  loop: "{{ interfaces_nat_inside }}"
  when: interfaces_nat_inside is defined

- name: "Creation de l'ACL pour le NAT (Module Declaratif)"
  cisco.ios.ios_acls:
    state: merged
    config:
      - afi: ipv4
        acls:
          - name: "{{ number_acl }}"
            acl_type: standard
            aces:
              - grant: permit
                source:
                  address: "{{ item.ip }} {{ item.wildcard_mask }}"
  loop: "{{ subnet_choose }}"
  when: 
    - subnet_choose is defined
    - number_acl is defined

- name: "Activation de la regle NAT Overload (PAT) avec translation de ports"
  cisco.ios.ios_config:
    lines:
      - "ip nat inside source list {{ number_acl }} interface {{ interface_nat_outside }} overload"
  when: 
    - interface_nat_outside is defined
    - number_acl is defined