# /home/elpetrino/projet/roles/router_provisioning/tasks/09-save.yml

- name: Sauvegarde de la configuration courante (copy run start)
  cisco.ios.ios_command:
    commands: write memory
  register: router_save

- name: Construction de la liste des modules effectivement executes
  ansible.builtin.set_fact:
    modules_appliques: >-s
      {%- set liste = [] -%}
      {%- if trigger_backup | default(true) %}{% set _ = liste.append('01-Backup') %}{% endif -%}
      {%- if trigger_hardening | default(false) %}{% set _ = liste.append('02-Hardening') %}{% endif -%}
      {%- if trigger_base_services | default(false) %}{% set _ = liste.append('03-Base_Services') %}{% endif -%}
      {%- if trigger_interfaces | default(false) %}{% set _ = liste.append('04-Interfaces') %}{% endif -%}
      {%- if trigger_routing | default(false) %}{% set _ = liste.append('05-Routing') %}{% endif -%}
      {%- if trigger_nat | default(false) %}{% set _ = liste.append('06-NAT') %}{% endif -%}
      {%- if trigger_acls | default(false) %}{% set _ = liste.append('07-ACLs') %}{% endif -%}
      {%- if trigger_dhcp | default(true) %}{% set _ = liste.append('08-DHCP') %}{% endif -%}
      {%- set _ = liste.append('09-Save') -%}
      {{ liste }}

- name: Retour de succes au format JSON pour l'application Web
  ansible.builtin.debug:
    msg:
      status: "success"
      device: "{{ inventory_hostname }}"
      message: "Le provisionnement et la sauvegarde ont ete executes avec succes."
      modules_executed: "{{ modules_appliques }}"