---
- name: "Execution du Module 1 : Backup"
  include_tasks: "01-Backup.yml"
  when: trigger_backup | default(true)

- name: "Execution du Module 2 : Hardening"
  include_tasks: "02-Hardening.yml"
  when: trigger_hardening | default(false)

- name: "Execution du Module 3 : Base Services"
  include_tasks: "03-Base_Services.yml"
  when: trigger_base_services | default(false)

- name: "Execution du Module 4 : Interfaces"
  include_tasks: "04-Interfaces.yml"
  when: trigger_interfaces | default(false)

- name: "Execution du Module 5 : Routing"
  include_tasks: "05-Routing.yml"
  when: trigger_routing | default(false)

- name: "Execution of nat installation"
  include_tasks: "06-acl_nat.yml"
  when: trigger_nat | default(false)

- name: "Execution of security acls"
  include_tasks: "07-acl_security.yml"
  when: trigger_acls | default(false)

- name: "Execution of dhcp"
  include_tasks: "08-dhcp.yml"
  when: trigger_dhcp | default(true)

- name: "Execution du Module 9 : Save"
  include_tasks: "09-save.yml"
  when: trigger_save | default(true)
 