---
- name: L2 PHASE creating de VLAN 
  cisco.ios.ios_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.id }}"
        state: active
    state: merged
  loop: "{{ all_vlans | default([]) }}"
  when: item.id in (vlan | default([]))

- name: L2 PHASE assigned access port to vlan
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{ item.name }}"
        mode: access
        access:
          vlan: "{{ item.id }}"
    state: merged
  loop: "{{ access_port | default([]) }}"

- name: L2 PHASE assigned trunk port (Secure & Pruned)
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{ item.name }}" 
        mode: trunk
        nonegotiate: true
        trunk:
          allowed_vlans: "{{ vlan | join(',') }}"
    state: merged
  loop: "{{ trunk_port | default([]) }}"  
