---
- name: L2 PHASE - Activation globale du DHCP Snooping sur TOUS les VLANs
  cisco.ios.ios_config:
    lines:
      - ip dhcp snooping
      - ip dhcp snooping vlan 1-4094

- name: L2 phase - activate dhcp snooping on trunk ports
  cisco.ios.ios_config:
    lines:
      - ip dhcp snooping trust
    parents: "interface {{ item.name }}"
  loop: "{{ trunk_port | default([]) }}"
  when: item.dhcp_trust | default(true) | bool

- name: L2 phase - desactivate dhcp snooping on access ports
  cisco.ios.ios_config:
    lines:
      - no ip dhcp snooping trust
    parents: "interface {{ item.name }}"
  loop: "{{ access_port | default([]) }}"
