---
- name: L2 PHASE - Storm Control pour les ports d'acces
  cisco.ios.ios_config:
    parents: "interface {{ item.name }}"
    lines:
      - storm-control broadcast level {{ item.storm_control.broadcast | default(10.0) }}
      - storm-control multicast level {{ item.storm_control.multicast | default(10.0) }}
      - storm-control unicast level {{ item.storm_control.unicast | default(10.0) }}
  loop: "{{ access_port }}"
  when: activate_storm_control | default(false) | bool and item.storm_control.enabled | default(false) | bool

- name: L2 PHASE - Storm Control pour les ports Trunks
  cisco.ios.ios_config:
    lines:
      - storm-control broadcast level {{ item.storm_control.broadcast | default(10.0) }}
      - storm-control multicast level {{ item.storm_control.multicast | default(10.0) }}
      - storm-control unicast level {{ item.storm_control.unicast | default(10.0) }}
    parents: "interface {{ item.name }}"
  loop: "{{ trunk_port | default([]) }}"
  when: 
    - item.storm_control is defined
    - item.storm_control.enabled | default(false) == true