---
- name: MANAGEMENT PHASE - Configuration du Hostname de l'appareil
  cisco.ios.ios_hostname:
    config:
      hostname: "{{ hostname }}"
  when: hostname is defined and hostname != ''

- name: MANAGEMENT PHASE - Desactivation du DNS lookup
  cisco.ios.ios_config:
    lines:
      - no ip domain lookup

- name: MANAGEMENT PHASE - Configuration du serveur NTP (si fourni)
  cisco.ios.ios_config:
    lines:
      - "ntp server {{ ntp_serveur | string | trim }}"
  when: ntp_serveur is defined and ntp_serveur | string | trim != '' and ntp_serveur != None

- name: MANAGEMENT PHASE - Configuration du confort CLI (Console)
  cisco.ios.ios_config:
    lines:
      - logging synchronous
      - exec-timeout 5 0
    parents: line con 0